### ISSUE TITLE
Peer to perr code review

### ISSUE THREAD

**Issue by NabilHY** [jasonfelice/Favorite-Books#2]
Hey Jason 
You have done an amazing job so far  👍 
Things to highlight :
> Webpage design and layout look amazing And the functionalities work perfectly.
But making some additional changes would improve your code structure and efficiently
          > Try adding some alert messages to the user whenever a book is added or removed, It would really ameliorate your user 
           experience.
          > Try to display an alert message whenever the user's value of the inputs is empty.
          >kindly consider adding main tag in your HTML as the parent element of section tags, as it would improve your code's 
            readability.

**Comment by jasonfelice** [comment]
Thank you! I appreciate you took the time to check out my project.
